//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiguzellikmerkezi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisanlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Calisanlar()
        {
            this.Hizmetlers = new HashSet<Hizmetler>();
        }
    
        public int CalisanNo { get; set; }
        public string CalisanAdi { get; set; }
        public Nullable<int> Yas { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public string Adres { get; set; }
        public Nullable<int> SalonNo { get; set; }
    
        public virtual Salonlar Salonlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hizmetler> Hizmetlers { get; set; }
    }
}
