//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiguzellikmerkezi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hizmetler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hizmetler()
        {
            this.Urunlers = new HashSet<Urunler>();
        }
    
        public int HizmetNo { get; set; }
        public string HizmetAdi { get; set; }
        public string HizmetAmaci { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<int> CalisanNo { get; set; }
    
        public virtual Calisanlar Calisanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urunler> Urunlers { get; set; }
    }
}
