//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiguzellikmerkezi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salonlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salonlar()
        {
            this.Calisanlars = new HashSet<Calisanlar>();
        }
    
        public int SalonNo { get; set; }
        public string SalonAdi { get; set; }
        public string CalisanSayisi { get; set; }
        public string VerilenHizmetler { get; set; }
        public string HizmetSayisi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calisanlar> Calisanlars { get; set; }
    }
}
